# Generated by Django 4.2.7 on 2023-11-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='liked',
            new_name='likes',
        ),
    ]
